### ISSUE TITLE
Unable to register extension org.sonar.plugins.objectivec.ObjectiveCSquidSensor from plugin 'backelitesonarobjectivecplugin'

### ISSUE THREAD

**Issue by azizur** [Backelite/sonar-objective-c#14]
Hi There,

I am trying use the current release `backelite-sonar-objective-c-plugin-0.5.1.jar` but when I try to run the scanner I am getting the following error.

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to register extension org.sonar.plugins.objectivec.ObjectiveCSquidSensor from plugin 'backelitesonarobjectivecplugin'
```

**Comment by zippy1978** [comment]
Hi,

Which version of SonarSube do you use ?

**Comment by kemalates** [comment]
I have the same error. I'm using SonarQube 6.1.

**Comment by azizur** [comment]
I am using SonarQube Version 6.1

**Comment by zippy1978** [comment]
Hi @azizur 

At the moment SonarQube 6.x is not supported by the plugin.
Support will come soon...

**Comment by zippy1978** [comment]
Hi @azizur,

I pushed SonarQube 6 suppot on branch feat/sonarqube6.
Everything seems to be ok, but I need to do some more testing before releasing it.

Gilles

**Comment by azizur** [comment]
Thank you @zippy1978 I will try it out and will let you know if I find issue.

**Comment by Narmatha** [comment]
Hi,
 I took code from branch feat/sonarqube6 and build jar. Its not working with sonarqube 6.1. Still i am getting same error. can you share me the jar file path to download? 
Thank you

**Comment by azizur** [comment]
@zippy1978 I am sorry I did not have anytime to check this. Looks like @Narmatha has check.

**Comment by geri-m** [comment]
@zippy1978 works fine with sonarqube 6.0; but lizard does not create the report.xml. Any ideas how to fix this issue?

**Comment by zippy1978** [comment]
Hi @geri-m ,

No idea : the generation of the report has nothing to do with SonarQube 6 support (it is called by the  run-sonar-swift.sh script).

Did you try to run the script in verbose mode ? (run-sonar-swift.sh -X)

**Comment by jmich41** [comment]
I'm using SonarQube 6.2 I compiled and installed this version and now script "run-sonar.sh" returns:
```
15:26:36.745 WARN  - Metric 'test_success_density' is an internal metric computed by SonarQube. Provided value is ignored.
15:26:36.747 ERROR - Can not parse surefire reports
java.lang.UnsupportedOperationException: Metric 'test_data' should not be computed by a Sensor
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:240)
	at org.sonar.scanner.index.DefaultIndex.addMeasure(DefaultIndex.java:231)
	at org.sonar.scanner.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:131)
	at org.sonar.plugins.objectivec.tests.SurefireParser.saveTestsDetails(SurefireParser.java:161)
	at org.sonar.plugins.objectivec.tests.SurefireParser.parseFiles(SurefireParser.java:129)
	at org.sonar.plugins.objectivec.tests.SurefireParser.collect(SurefireParser.java:78)
	at org.sonar.plugins.objectivec.tests.SurefireSensor.collect(SurefireSensor.java:86)
	at org.sonar.plugins.objectivec.tests.SurefireSensor.analyse(SurefireSensor.java:80)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
```

**Comment by jmich41** [comment]
looks like similar bug: https://github.com/Backelite/sonar-swift/issues/61

**Comment by zippy1978** [comment]
Hi,

Release [0.6.0](https://github.com/Backelite/sonar-objective-c/releases/tag/0.6.0) is now working with SonarQube 6.0 to 6.2.

Regards,
Gilles
