### ISSUE TITLE
NPE in DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:127) called from org.sonar.plugins.objectivec.tests.SurefireParser.saveClassMeasure(SurefireParser.java:167)

### ISSUE THREAD

**Issue by ultraon** [Backelite/sonar-objective-c#24]
Hello all, any body get such error while parsing unit test report by sonar-scanner/sonar-runner (the same result for both)?

```
...
12:19:15.967 DEBUG: Sensors : ObjectiveCSquidSensor -> Objective-C SurefireSensor -> org.sonar.plugins.objectivec.coverage.CoberturaSensor@216e9ca3 -> org.sonar.plugins.objectivec.violations.oclint.OCLintSensor@75120e58 -> org.sonar.plugins.objectivec.violations.fauxpas.FauxPasSensor@48976e6d -> org.sonar.plugins.objectivec.complexity.LizardSensor@2a367e93 -> Coverage Report Import -> Coverage Report Import -> Unit Test Results Import -> XmlFileSensor
12:19:15.967 INFO: Sensor ObjectiveCSquidSensor
12:19:16.226 DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
12:19:16.228 DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
12:19:16.229 INFO: Sensor ObjectiveCSquidSensor (done) | time=262ms
12:19:16.229 INFO: Sensor Objective-C SurefireSensor
12:19:16.229 INFO: parsing sonar-reports
12:19:16.483 ERROR: Can not parse surefire reports
java.lang.NullPointerException: null
	at org.sonar.scanner.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:127) ~[sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.plugins.objectivec.tests.SurefireParser.saveClassMeasure(SurefireParser.java:167) [backelite-sonar-objective-c-plugin-0.6.0.jar:na]
	at org.sonar.plugins.objectivec.tests.SurefireParser.parseFiles(SurefireParser.java:119) [backelite-sonar-objective-c-plugin-0.6.0.jar:na]
	at org.sonar.plugins.objectivec.tests.SurefireParser.collect(SurefireParser.java:78) [backelite-sonar-objective-c-plugin-0.6.0.jar:na]
	at org.sonar.plugins.objectivec.tests.SurefireSensor.collect(SurefireSensor.java:86) [backelite-sonar-objective-c-plugin-0.6.0.jar:na]
	at org.sonar.plugins.objectivec.tests.SurefireSensor.analyse(SurefireSensor.java:80) [backelite-sonar-objective-c-plugin-0.6.0.jar:na]
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118) [sonar-scanner-engine-shaded-6.1.jar:na]
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch2111111682724345271.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-cli-2.8.jar:na]
	at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonar-scanner-cli-2.8.jar:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-2.8.jar:na]
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110) [sonar-scanner-cli-2.8.jar:na]
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74) [sonar-scanner-cli-2.8.jar:na]
	at org.sonarsource.scanner.cli.Main.main(Main.java:61) [sonar-scanner-cli-2.8.jar:na]

12:19:16.518 INFO: ------------------------------------------------------------------------
12:19:16.518 INFO: EXECUTION FAILURE
12:19:16.518 INFO: ------------------------------------------------------------------------
12:19:16.519 INFO: Total time: 15.582s
12:19:16.719 INFO: Final Memory: 43M/113M
12:19:16.719 INFO: ------------------------------------------------------------------------
12:19:16.720 ERROR: Error during SonarQube Scanner execution
org.sonar.api.utils.XmlParserException: Can not parse surefire reports
	at org.sonar.plugins.objectivec.tests.SurefireParser.parseFiles(SurefireParser.java:137)
	at org.sonar.plugins.objectivec.tests.SurefireParser.collect(SurefireParser.java:78)
	at org.sonar.plugins.objectivec.tests.SurefireSensor.collect(SurefireSensor.java:86)
	at org.sonar.plugins.objectivec.tests.SurefireSensor.analyse(SurefireSensor.java:80)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NullPointerException
	at org.sonar.scanner.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:127)
	at org.sonar.plugins.objectivec.tests.SurefireParser.saveClassMeasure(SurefireParser.java:167)
	at org.sonar.plugins.objectivec.tests.SurefireParser.parseFiles(SurefireParser.java:119)
	... 32 more
```

**Comment by mfominov** [comment]
I faced with same problem.
Try to look at your tests files in my case
SPEC_BEGIN(*Spec) and the file name was not contained Spec was *.m

**Comment by divyanshyadav** [comment]
Facing the same issue. Any solution?

**Comment by gtatgh** [comment]
I think this is the same issue as #39.

**Comment by ultraon** [comment]
As i know there is only option: Install SonarQube 5.6v LTS, we will reconfigure our server with this version.

**Comment by zippy1978** [comment]
Hi,

Release 0.6.2 now support SonarQube 6.5.

regards,
Gilles
