### ISSUE TITLE
Fauxpas upload to sonar server is error

### ISSUE THREAD

**Issue by linwenbang** [Backelite/sonar-objective-c#27]
i use 1.7.1 fauxpas cli

./run-sonar.sh

```
-n Running SonarQube using SonarQube Runner
-n .
-n .
-n .
ERROR: Error during SonarQube Scanner execution
ERROR: null
ERROR:
ERROR: To see the full stack trace of the errors, re-run SonarQube Scanner with the -e switch.
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-runner ' failed with error code: 1
```

After this， I try sonnar-runner -X

```
NFO: Processing FauxPas report sonar-reports/fauxpas.json
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 19.404s
INFO: Final Memory: 57M/693M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
  at org.sonar.scanner.index.BatchComponentCache.get(BatchComponentCache.java:50)
  at org.sonar.scanner.deprecated.perspectives.BatchPerspectives.as(BatchPerspectives.java:63)
  at org.sonar.plugins.objectivec.violations.fauxpas.FauxPasReportParser.recordIssue(FauxPasReportParser.java:90)
  at org.sonar.plugins.objectivec.violations.fauxpas.FauxPasReportParser.parseReport(FauxPasReportParser.java:72)
  at org.sonar.plugins.objectivec.violations.fauxpas.FauxPasSensor.parseReportIn(FauxPasSensor.java:83)
  at org.sonar.plugins.objectivec.violations.fauxpas.FauxPasSensor.analyse(FauxPasSensor.java:68)
  at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
  at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
  at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
  at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
  at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
  at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
  at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
  at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
  at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
  at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
  at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
  at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
  at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
  at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
  at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
  at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
  at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
  at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
  at com.sun.proxy.$Proxy0.execute(Unknown Source)
  at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
  at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
  at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
  at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:118)
  at org.sonarsource.scanner.cli.Main.execute(Main.java:80)
  at org.sonarsource.scanner.cli.Main.main(Main.java:66)
```

It is a bug? How coulde i fix this?

**Comment by ghost** [comment]
Seems to be an incompatibility between  this sonar plugin and fauxpas > 1.6.2.

With fauxpas 1.6.2 : works like a charm.
With fauxpas 1.7.1 : this error occured.

May be [fauxpas release](http://fauxpasapp.com/releases/) help us : 

> New rule: Spelling error.
> New rule: Source file header comment format.
> New rule: Erroneous view layout in XIB.
> New rule: Cyclomatic Complexity.

**Comment by zippy1978** [comment]
Hi,
I just tested with FauxPas 1.7.2 and Xcode 9 and it works ok.

@linwenbang could you test again with plugin version 0.6.2 and FauxPas 1.7.2 ?

Gilles
