### ISSUE TITLE
Metric 'file_complexity' should not be computed by a Sensor

### ISSUE THREAD

**Issue by nanomb** [Backelite/sonar-objective-c#28]
When running the sonar scanner through Fastlae, I'm getting this error for all my objc files:

    [01:13:47]: ▸ ERROR:  Exception -> ./MyProject/Code/Domain/Interactors/Taxes/MyFile.m -> Complexity / File
    [01:13:47]: ▸ java.lang.UnsupportedOperationException: Metric 'file_complexity' should not be computed by a Sensor
    [01:13:47]: ▸ at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:248)
    [01:13:47]: ▸ at org.sonar.scanner.index.DefaultIndex.addMeasure(DefaultIndex.java:155)
    [01:13:47]: ▸ at org.sonar.scanner.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:126)
    [01:13:47]: ▸ at org.sonar.plugins.objectivec.complexity.LizardMeasurePersistor.saveMeasures(LizardMeasurePersistor.java:80)
    [01:13:47]: ▸ at org.sonar.plugins.objectivec.complexity.LizardSensor.analyse(LizardSensor.java:80)
    [01:13:47]: ▸ at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
    [01:13:47]: ▸ at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
    [01:13:47]: ▸ at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
    [01:13:47]: ▸ at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
    [01:13:47]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
    [01:13:47]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
    [01:13:47]: ▸ at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
    [01:13:47]: ▸ at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
    [01:13:47]: ▸ at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
    [01:13:47]: ▸ at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
    [01:13:47]: ▸ at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
    [01:13:47]: ▸ at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
    [01:13:47]: ▸ at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
    [01:13:47]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [01:13:47]: ▸ at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [01:13:47]: ▸ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [01:13:47]: ▸ at java.lang.reflect.Method.invoke(Method.java:498)
    [01:13:47]: ▸ at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    [01:13:47]: ▸ at com.sun.proxy.$Proxy0.execute(Unknown Source)
    [01:13:47]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
    [01:13:47]: ▸ at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    [01:13:47]: ▸ at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
    [01:13:47]: ▸ at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
    [01:13:47]: ▸ at org.sonarsource.scanner.cli.Main.main(Main.java:61)

This is my lane:

     lane :metrics do
      scan(
        scheme: "MyScheme",
        clean: true,
        code_coverage: true,
        output_directory: "sonar-reports",
        output_types: "junit,json-compilation-database",
        buildlog_path: "sonar-reports",
        derived_data_path: "sonar-reports",
        use_clang_report_name: true,
        custom_report_file_name: "TEST-report.xml",
        xcargs: "ONLY_ACTIVE_ARCH=YES"
      )
      slather(
        simple_output: true,
        cobertura_xml: true,
        output_directory: "sonar-reports",
        proj: "MyProject.xcodeproj",
        scheme: "MyScheme",
        build_directory: "sonar-reports",
        ignore: ["../../../Applications/Xcode.app/*", "../../../../../Applications/Xcode.app/*", "Vendors/*", "Crashlytics.framework/*"]
      )
      sh(
        "cd .. && lizard . --xml > ./sonar-reports/lizard-report.xml"
      )
      oclint(
        compile_commands: "sonar-reports/compile_commands.json",
        report_type: 'pmd',
        select_regex: /MyProject/,
        max_priority_1: 10,
        max_priority_2: 5000,
        max_priority_3: 50000,
        enable_clang_static_analyzer: false,
        allow_duplicated_violations: false,
        list_enabled_rules: true,
        report_path: "sonar-reports/oclint.xml"
      )
      sonar
      end

**Comment by nanomb** [comment]
Duplicated. Closing it. #21
