### ISSUE TITLE
Compatibility with Sonar 6.4

### ISSUE THREAD

**Issue by elshev** [Backelite/sonar-objective-c#39]
I've got the error starting Sonar 6.4 with sonar-objective-c plugin:
.....
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

Looks like the same error as in https://github.com/Backelite/sonar-swift/issues/90

**Comment by gtatgh** [comment]
I have the same error with sonar version 6.5 and plugin version 0.6.1
<details>

```
2017.08.16 10:22:35 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin ObjectiveC [backelitesonarobjectivecplugin]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:531)
	at org.sonar.server.platform.Platform.start(Platform.java:231)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:205)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$1$$Lambda$44/1463253878.run(Unknown Source)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/CodeColorizerFormat
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.objectivec.ObjectiveCPlugin.getExtensions(ObjectiveCPlugin.java:53)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:78)
	... 10 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 26 common frames omitted
2017.08.16 10:22:35 INFO  web[][o.s.p.StopWatcher] Stopping process
2017.08.16 10:22:35 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
```

</details>

**Comment by pbernery** [comment]
Indeed, probably same error as https://github.com/Backelite/sonar-swift/issues/90.
We are investigating the issue.

**Comment by hameno** [comment]
Any update on this? Looks like the problem has been fixed in the swift plugin, can a new release for this plugin also be done?

**Comment by JackLeo** [comment]
If no work is being done here, can the underlying problem be explained here so someone could do a pull request? Swift task did not have a PR to compare against.

**Comment by hgrimberg01** [comment]
In my quick look, it looks like the underlying API that is being used has been deprecated for some time and was removed in later versions of Sonarqube.

**Comment by pingadi** [comment]
any update on this issue?

**Comment by divyanshyadav** [comment]
Facing the same issue.

**Comment by ultraon** [comment]
As i know there is only option: Install SonarQube 5.6v LTS, we will reconfigure our server with this version.

**Comment by JackLeo** [comment]
It looks like Backerlite has moved completely to swift thus this project is abandoned.

**Comment by CoreOne23** [comment]
Sonar 6.5 is not going up after adding backelite-sonar-objective-c-plugin-0.6.1.jar to the plugin folder. Anyone facing the same issue?

**Comment by andrewclaus** [comment]
Also hoping for Sonar 6.5 support soon... our company just updated and the plugin stopped working.

**Comment by andrewclaus** [comment]
This PR reportedly got the swift version working with Sonar 6.4+, will it get it working for us also? https://github.com/Backelite/sonar-swift/pull/94

I know we still have a lot of old APIs being used, but so does the Swift version, yet it works OK.

**Comment by andrewclaus** [comment]
I was able to get the plugin working by adding the same fix that got the swift version working, adding the missing dependency to the POM.

```
<dependency>
    <groupId>org.sonarsource.sonarqube</groupId>
    <artifactId>sonar-plugin-api</artifactId>
    <version>6.3</version>
</dependency>
```

You can do this yourself by downloading the latest source code of this plugin, adding these lines to the  end of the dependency list in the pom.xml file, then recompiling using maven. I had to install maven with "brew install maven" on osx. 

I will try to create a pull request that has this change. Update: https://github.com/Backelite/sonar-objective-c/pull/48

**Comment by CoreOne23** [comment]
@andrewclaus  could you please tell me how to compile the pom.xml. Like I downloaded the plugin jar and unzipped it and gone to the pom location and executed ` mvn clean package`  after adding the above dependency code. But that gives me an error like 

>  on project backelite-sonar-objective-c-plugin: Plugin class not found: 'org.sonar.plugins.objectivec.ObjectiveCPlugin
### 
And another doubt, if it successfully compiles the pom , will create a separate jar file for the plugin or should I wrap again the original plugin folder?

**Comment by andrewclaus** [comment]
@CoreOne23 The steps I took are:
1. Download the full source code from this repository (not just the packaged jar).
2. Update the pom.xml file with the dependency listed above (add it to the end of the list of dependencies)
3. Install maven if it is not already with "brew install maven"
4. compile with maven "mvn clean install -Danimal.sniffer.skip=true" (it had an error with the animal sniffer if I did not disable it)
5. the new jar is created, drop this into the sonar plugins folder.

**Comment by CoreOne23** [comment]
@andrewclaus  thank you very much. `maven clean install ` alone worked, I think (as there displayed obj c profiles in my sonarqube).  But now I am getting this error. Has anyone faced this issue for oclint db command during analysis?

> error: one compiler command contains multiple jobs:

**Comment by JackLeo** [comment]
@andrewclaus thanks for the workaround. Seems to be working

**Comment by gsgtzq** [comment]
@CoreOne23 @andrewclaus thank you so much, I added missing dependency to the POM and use command `mvn clean install -Danimal.sniffer.skip=true` to build jar file, it's worked!

**Comment by zippy1978** [comment]
Hi all,

Version 0.6.2 of the plugin now supports SonarQube 6.4 and 6.5 (minimum version is now 5.6).

Regards,
Gilles
