### ISSUE TITLE
 Fail to load plugin ObjectiveC [backelitesonarobjectivecplugin] In SonarQube 6.7

### ISSUE THREAD

**Issue by ElesG** [Backelite/sonar-objective-c#49]
Hi,
 configure list:
 Mac OS 10.13.1
 Xcode9.1
 SonarQube 6.7（docker）/ SonarQube 6.5（hostmachine）
 jdk1.8.1
 Before I put  this plugin jar in the /plugins, sonarqube worked.
 Once I put this plugin jar in the /plugins, sonarqube can not restart success and get some error.
 I had tried many ways but not worked, Please help.
java.lang.IllegalStateException: Fail to load plugin ObjectiveC [backelitesonarobjectivecplugin]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:531)
	at org.sonar.server.platform.Platform.start(Platform.java:231)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:205)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/CodeColorizerFormat
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.objectivec.ObjectiveCPlugin.getExtensions(ObjectiveCPlugin.java:53)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:78)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

**Comment by rompic** [comment]
it seems as if only one dependency is missing

see the fixes in these forks: 
https://github.com/andrewclaus/sonar-objective-c/commit/da201e1bfbcae48934b4df201db15392d986ab2e

https://github.com/skroutz/sonar-objective-c/commit/9b8fba442f1e7ac24d271486f9c1da3d70e217ec

@zippy1978 
can you by any chance look into that?

**Comment by rompic** [comment]
also see https://github.com/Backelite/sonar-swift/issues/90 for reference

**Comment by zippy1978** [comment]
Hi,

Version 0.6.3 now supports SonarQube 6.7

Regards,
gilles

**Comment by rompic** [comment]
Thx for the fast response! Highly appreciated

**Comment by ElesG** [comment]
Thanks for your assistance! @rompic @zippy1978 ☺☺
